# Generated by Django 4.2.11 on 2024-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("1", "Superadmin"), ("2", "Admin"), ("3", "Employee")],
                max_length=15,
            ),
        ),
    ]
